### ISSUE TITLE
V.1.2.3 conflicts with Temporary Container add-ons (any) (Priority level: High)

### ISSUE THREAD

**Issue by EstherMoellman** [ThomazPom/Moz-Ext-UltimaDark#28] opened 2020-08-03 00:24 UTC

**Comment by ThomazPom** [comment] 2020-08-03 19:04
May this be only your cache ?

**Comment by EstherMoellman** [comment] 2020-08-03 20:26
Hi @ThomazPom !

It took me time, but I found the culprit: Is a conflict between UltimaDark V1.2.3 and Temporary Container add-ons (any).

Way to reproduce:
- Install latest Nightly
- Install UltimaDark V1.2.3
- Install https://addons.mozilla.org/en-US/firefox/addon/temporary-containers (or https://addons.mozilla.org/en-US/firefox/addon/tabcontainer)

Result: Every new tab need to press "enter" (at least) twice.

Disable UltimaDark V1.2.3 and everything works fine.
Or keep Ultima enabled and disabled Temporary Container add-on, and everything works fine.

**Comment by EstherMoellman** [comment] 2020-08-13 20:42
V1.2.8 is has an improvement in this issue. Now all tabs are opened pressing "enter" one time.
However and unfortunately, if UltimaDark is enabled with a Container add-on, then lot of pages are broken, or aren't darkened.

**Comment by EstherMoellman** [comment] 2020-08-13 21:13
I opened an issue: https://github.com/sagitta1618/tabContainer/issues/8

**Comment by EstherMoellman** [comment] 2020-08-14 11:10
Curious event worth mentioning:
Latest versions of UltimaDark were consuming around (±) 2.3MB of RAM. V1.2.9 was the highest, with (±) 3MB.
However, when containers are enabled, V1.2.9 RAM consumption drops to (±) 2MB. Unfortunately the UltimaDark and Containers conflict still exists, and if both are enabled then pages are broken or not darkened. But the drop in RAM consumption seems interesting, and I hope in the future might be useful to improve UltimaDark' RAM.

PS: It's not really the RAM consumption that matters. If UltimaDark consumes 1000GB RAM, and this makes UltimaDark better and faster, then I don't care!, RAM is there to be consumed, is fine to consume RAM. The problem is that RAM consumption in most of the cases is also related to CPU use... and this is the problem... because CPU interferes with browser performance, kills battery, generates hit etc etc etc.

**Comment by ThomazPom** [comment] 2020-08-31 13:35
Hey
In previous versions, UltimaDark was blocking any addon request for technical reasons (It was atempting to block its own unwanted side loads) .
This issue may be fixed.

Thank you again for your work.

**Comment by ThomazPom** [comment] 2020-08-31 13:39
About the ram, UD uses the ram to lower cpu usage, as once the darkening of a color is pre calculated, the cpu wont have to do it again. 
There is still a LOT of possible optimization but i'm working on nice aestetics first, because optimization is (for me) the easy part

**Comment by EstherMoellman** [comment] 2020-08-31 17:57
Hi @ThomazPom !
Just to keep you informed, unfortunately the conflict between UD and Temporary Container add-ons... still is there.
Anyway, zillions of thanks for your fantastic work.
Big hug! : )

**Comment by ThomazPom** [comment] 2023-12-10 15:41
Hi
I tested multiple, and i can't reproduce this issue.

**Comment by ThomazPom** [comment] 2023-12-11 22:39
Can't reproduce, closing

**Closed by ThomazPom** 2023-12-11 22:39 UTC
