### ISSUE TITLE
Webpage menu/headings/formatting text misaligns

### ISSUE THREAD

**Issue by audio101** [ThomazPom/Moz-Ext-UltimaDark#80] opened 2024-06-30 02:36 UTC
Many websites page text menu/heading/spacing/alignment changes & goes all out of whack on some sites when enabled.

**Comment by Vintagemotors** [comment] 2024-07-02 18:01
While I haven't seen that, I have seen reversions to base html (open issue). Please provide specific examples.

**Comment by Vintagemotors** [comment] 2024-09-25 18:39
@audio101 Closing in 2 weeks if this is no longer an issue or no examples are provided.

**Comment by ThomazPom** [comment] 2024-09-26 06:54
This issue is not relevant, since we have a broken sites issue and this bug is too broad and could have been caused by any part of the code including fixed ones in the past 25 days. Closing now

**Closed by ThomazPom** 2024-09-26 06:54 UTC
